# Generated by Django 5.2.3 on 2025-06-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demo', '0004_alter_emailverification_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telegrambot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(max_length=50)),
            ],
        ),
    ]
